### ISSUE TITLE
Bug in reference counting or garbage collection

### ISSUE THREAD

**Issue by prpr19xx** [msteveb/jimtcl#245]
The following is a much simplified test case (I didn't write the original) for something which used to work at least in 0.78 and doesn't work since at least 0.81 (haven't checked interim versions).
```
package require oo

class t { val 0 }
t method setval {v} { set val $v }

proc final {ref value} { puts "Destroy $ref" }

set l1 [list 99 96 98 97]
set l2 [lmap i $l1 {
        set tt [t new]
        finalize $tt final
        puts "Create $tt"
        $tt setval $i
        list $tt
    }]
set getter [lambda {t} { list [$t get val] }]
set entries [lsort -command \
    [lambda {a b} {upvar getter g; expr {[$g $a] - [$g $b]}}] $l2]

puts "Display"
foreach e $entries { puts "$e [$e get val]" }
puts "Before collect"
collect
puts "After collect"
puts $entries
```

This generates the following (with a JIM_DEBUG_GC build):
```
Create ::<reference.<t______>.00000000000000000000>
Create ::<reference.<t______>.00000000000000000002>
Create ::<reference.<t______>.00000000000000000004>
Create ::<reference.<t______>.00000000000000000006>
Display
::<reference.<t______>.00000000000000000002> 96
::<reference.<t______>.00000000000000000006> 97
::<reference.<t______>.00000000000000000004> 98
::<reference.<t______>.00000000000000000000> 99
Before collect
MARK (reference): 10 refcount: 1
MARK: 8 (type=command)
MARK: 6 (type=command)
MARK: 6 (type=command)
No MARK: 4 - command with refcount=1
No MARK: 4 - command with refcount=1
No MARK: 2 - command with refcount=1
No MARK: 2 - command with refcount=1
No MARK: 0 - command with refcount=1
No MARK: 0 - command with refcount=1
COLLECTING 2
Destroy <reference.<t______>.00000000000000000002>
COLLECTING 4
Destroy <reference.<t______>.00000000000000000004>
COLLECTING 0
Destroy <reference.<t______>.00000000000000000000>
After collect
::<reference.<t______>.00000000000000000002> ::<reference.<t______>.00000000000000000006> ::<reference.<t______>.00000000000000000004> ::<reference.<t______>.00000000000000000000>
```
which destroys objects when it shouldn't and causes subsequent code to crash (not shown here).
Do those doubled lines suggest possibly something should be creating a single entry with refcount=2 rather than two entries with a refcount=1 ?
If I comment out the ```set entries``` stuff then it displays this:
```
Create ::<reference.<t______>.00000000000000000000>
Create ::<reference.<t______>.00000000000000000002>
Create ::<reference.<t______>.00000000000000000004>
Create ::<reference.<t______>.00000000000000000006>
Before collect
MARK (reference): 8 refcount: 2
MARK: 6 (type=command)
MARK: 4 (type=command)
MARK: 2 (type=command)
MARK: 0 (type=command)
After collect
```
which is what I would expect.
I don't think the problem is in the garbage collection itself but somewhere further back in the lifetime tracking. Debugging this is beyond my current understanding.

Also, should the value of $ref passed to the finalize function contain a leading "::" or not?

**Comment by prpr19xx** [comment]
This is even simpler:
```
package require oo

class t { val 0 }
t method setval {v} { set val $v }

proc final {ref value} { puts "Destroy $ref" }

set l1 [list 99 96 98]
set entries [lmap i $l1 {
        set tt [t new]
        finalize $tt final
        puts "Create $tt"
        $tt setval $i
        list $tt
    }]
puts "Collect A"
collect
puts "Display"
set e [lindex $entries 1]
puts $e
puts [$e classname]
puts "Collect B"
collect
```
and generates this (with a slight mod. to the GC debugging to show refCount):
```
Create ::<reference.<t______>.00000000000000000000>
Create ::<reference.<t______>.00000000000000000002>
Create ::<reference.<t______>.00000000000000000004>
Collect A
MARK: 4 (type=command) refCount=3
MARK: 2 (type=command) refCount=2
MARK: 0 (type=command) refCount=2
Display
::<reference.<t______>.00000000000000000002>
t
Collect B
MARK: 4 (type=command) refCount=3
No MARK: 2 objPtr->refCount=2 - command with refcount=1
No MARK: 2 objPtr->refCount=1 - command with refcount=1
MARK: 0 (type=command) refCount=2
COLLECTING 2
Destroy <reference.<t______>.00000000000000000002>
```
It seems that reading any property of $e causes the problem, as it goes away if commented out.
Changing the value of the lindex index to 2 doesn't break it, but 0 and 1 do.
Not sure why object "4" has different refCount to the other two either, but probably explains the preceding sentence.

**Comment by msteveb** [comment]
It does look like there is something not quite right there. I pushed a tentative fix to the branch garbage-collection-fix. Would you mind trying it out and let me know what you think?

**Comment by prpr19xx** [comment]
The output is now not showing any destruction, which is good:
```
Create ::<reference.<t______>.00000000000000000000>
Create ::<reference.<t______>.00000000000000000002>
Create ::<reference.<t______>.00000000000000000004>
Collect A
MARK: 4 (type=command) refCount=3
MARK: 2 (type=command) refCount=2
MARK: 0 (type=command) refCount=2
Display
::<reference.<t______>.00000000000000000002>
t
Collect B
MARK: 4 (type=command) refCount=3
MARK: 2 (type=command) refCount=2
No MARK: 2 - command with refcount=1
MARK: 0 (type=command) refCount=2
```
Still not sure if the refCount stuff is correct as I don't understand it (I tried selected old versions, back to about 2011 until they wouldn't compile, and it's always done that), but certainly the big problem is apparently fixed.

**Comment by msteveb** [comment]
Thanks. I'll try to come up with some unit tests that show both original problems before I merge it

**Comment by prpr19xx** [comment]
Not sure why me merging this fix into my personal fork should have closed the issue in the upstream repository when it hasn't been committed to upstream master.

**Comment by msteveb** [comment]
Sure. I don't know why either. I still want to create some unit tests to confirm that the fix is correct before I merge.

**Comment by Mar181-arc** [comment]
[![Code scanning - action](https://github.com/desktop/desktop/actions/workflows/codeql.yml/badge.svg)](https://github.com/desktop/desktop/actions/workflows/codeql.yml)

**Comment by msteveb** [comment]
I believe I now have a better fix for this problem (garbage-collection-fix-take2) taking into account that there can be multiple objects that refer to the same reference. I think it will end up the same, but this approach makes more sense to me.
