### ISSUE TITLE
file.test fail on 32 bit systems

### ISSUE THREAD

**Issue by yuzibo** [msteveb/jimtcl#263]
hi,
I just upload the 0.82 to Debian(sorry, I did not catch up bookworm release, but I can do bookworm-pu) and I found 
one of tests of file.test was failed:
```
error: mtime: file stat:1677290991 != aio stat:1686860085
```
The log maybe is helpful:
https://buildd.debian.org/status/fetch.php?pkg=jimtcl&arch=i386&ver=0.82-1&stamp=1686860099&raw=0
https://buildd.debian.org/status/package.php?p=jimtcl&suite=experimental

I do not have 32 bit system that which was supported by Debian by hand now, so I do not dig it deeply now.
Could you have a look?
please let me know if there is any issue.
Thanks.

**Comment by msteveb** [comment]
Thanks for the report.
I can see it's even worse on 32 bit arm.

```
error: size: file stat:13493 != aio stat:0
error: mtime: file stat:1677290991 != aio stat:32
```
It's clear that there is some mismatch. Perhaps 32 bit vs 64 bit stat.
I'll take a closer look. I have a few 32 bit ARM systems around.

**Comment by msteveb** [comment]
I pushed something to branch file-stat64 to try
This helped on the one 32 bit system I have access to right now (Linux pvr 3.5.1 #2 Wed May 20 14:06:48 AEST 2015 armv5teb GNU/Linux, uclibc)
YMMV

**Comment by yuzibo** [comment]
thanks. 
I try to build it on i386 again, but it seems have issue still:
```
../jim-file.c:189:49: error: invalid use of incomplete typedef 'jim_stat_t' {aka 'const struct stat64'}
  189 |     AppendStatElement(interp, listObj, "dev", sb->st_dev);
      |                                                 ^~
../jim-file.c:190:49: error: invalid use of incomplete typedef 'jim_stat_t' {aka 'const struct stat64'}
  190 |     AppendStatElement(interp, listObj, "ino", sb->st_ino);
...
```
https://salsa.debian.org/debian/jimtcl/-/jobs/4329769

**Comment by msteveb** [comment]
Hmm, that's interesting. In installed debian bookworm i386 in a VM and tested it with and without the patch.
Definitely has the problem without the patch but with the patch it compiled and ran perfectly.
I wonder why you are getting those compile errors.

**Comment by yuzibo** [comment]
Ok, thanks for confirming this.
Maybe the debian/rules cause the build error, I will look at this.
